# Definitions
definitions:

  # Page title with site name
  - &page_title_with_site_name >-
    {%- if not page.is_homepage -%}
      {{ page.meta.get("title", page.title) }} - {{ config.site_name }}
    {%- else -%}
      {{ page.meta.get("title", page.title) }}
    {%- endif -%}

  # Page description
  - &page_description >-
    {{ page.meta.get("description", config.site_description) or "" }}

# Meta tags
tags:

  # Open Graph
  og:type: website
  og:title: *page_title_with_site_name
  og:description: *page_description
#  og:image: "{{ image.url }}"
#  og:image:type: "{{ image.type }}"
#  og:image:width: "{{ image.width }}"
#  og:image:height: "{{ image.height }}"
  og:url: "{{ page.canonical_url }}"
