site_name: map5topo.nl
site_description: "map5topo is a topographic map of the Netherlands made with OpenStreetMap and Dutch Open Datasets"
site_author: Just van den Broecke
copyright: "&copy; 2023 Just Objects B.V."
site_url: https://map5topo.nl
repo_url: https://github.com/map5nl/map5topo.nl
edit_uri: '/docs/src'
docs_dir: src
nav:
    - Home: index.md
    - Design:
        - Specification: design/spec.md
        - Data: design/data.md
    - Creation:
        - Method: create/method.md
        - Setup: create/setup.md
        - Data: create/data.md
        - Map: create/map.md
    - Gallery:
        - Overview: gallery/index.md
        - 2022: gallery/2022.md
        - 2023: gallery/2023.md
    - Research: research.md

use_directory_urls: true

theme:
    name: material
    palette:
        # See https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-scheme
        # Default is indigo (blue)
        scheme: map5topo
    features:
        - navigation.sections
    favicon: assets/favicon.ico
    logo: assets/images/map5-logo-bg-black.png

plugins:
    - search
    - mkdocs-video
    - glightbox:
        touchNavigation: true
        loop: false
        effect: zoom
        slide_effect: slide
        width: 100%
        height: auto
        zoomable: true
        draggable: true
        skip_classes:
          - skip-lightbox
        auto_caption: false
        caption_position: bottom

markdown_extensions:
    - meta # option to add some meta tags on top, title, author, date, etc
    - admonition # adds the note, question, tip boxes, eg: !!! tip "my tip"
    - pymdownx.details # advanced collapsible panels
    - pymdownx.superfences # advanced features; such as line number, flow chart, python shell
    - footnotes # notes bottom of page
    - attr_list # used to size images
    - md_in_html # used to size images

extra_css:
    # light and dark variations from material.io
    # https://material.io/resources/color/#!/?view.left=0&view.right=1
    - assets/stylesheets/termynal.css
    - assets/stylesheets/custom.css

extra_javascript:
    - assets/javascripts/termynal.js
    - assets/javascripts/custom.js
